### ISSUE TITLE
Run ProperTree for linux

### ISSUE THREAD

**Issue by siralexmu** [Broly1/tribeam#3]
Hi Broly1,
I've installed python3 on my linux. How can I run ProperTree on linux?

**Comment by Broly1** [comment]
On Ubuntu you have to change `` #!/usr/bin/env python`` to  ``#!/usr/bin/env python3`` and install ``tk`` module  if you use python3 do ``apt install python3-tk`` for python2 do ``apt install python2.7-tk`` depending on the distro you are using it may be slightly different , the run `` ./ProperTree.command`` no root required

**Comment by Broly1** [comment]
> Hi Broly1,
> I've installed python3 on my linux. How can I run ProperTree on linux?

On Ubuntu you have to change `` #!/usr/bin/env python`` to  ``#!/usr/bin/env python3`` and install ``tk`` module  if you use python3 do ``apt install python3-tk`` for python2 do ``apt install python2.7-tk`` depending on the distro you are using it may be slightly different , the run `` ./ProperTree.command`` no root required

**Comment by siralexmu** [comment]
> > Hi Broly1,
> > I've installed python3 on my linux. How can I run ProperTree on linux?
> 
> On Ubuntu you have to change the first line of the script from
> ` #!/usr/bin/env python` to `#!/usr/bin/env python3` and install `tk` module if you use python3 do `apt install python3-tk` for python2 do `apt install python2.7-tk` depending on the distro you are using or python version it may be slightly different , then run ` ./ProperTree.command` no root required

Thank you Broly1,
I created a bootable hackintosh catalina on my USB and followed the OpenCore desktop guide. But after picking up "macOS Base System (external)", I got a black screen. I'm stuck and don't know what to do. Could you help me, please? I attached my laptop hardinfo.txt and config.plist files. Thank you very much!
Additional info: 
* In EFI/OC/Drivers directory, I have: HfsPlus.efi  OpenRuntime.efi  VBoxHfs.efi.
* In EFI/OC/Kexts directory, I have: AppleALC.kext, RealtekRTL8111.kext, WhateverGreen.kext, Lilu.kext, VirtualSMC.kext.
[hardinfo_config.zip](https://github.com/Broly1/tribeam/files/4644926/hardinfo_config.zip)

**Comment by Broly1** [comment]
> 
> Thank you Broly1,
> I created a bootable hackintosh catalina on my USB and followed the OpenCore desktop guide. But after picking up "macOS Base System (external)", I got a black screen. I'm stuck and don't know what to do. Could you help me, please? I attached my laptop hardinfo.txt and config.plist files. Thank you very much!
> Additional info:
> 
> * In EFI/OC/Drivers directory, I have: HfsPlus.efi  OpenRuntime.efi  VBoxHfs.efi.
> * In EFI/OC/Kexts directory, I have: AppleALC.kext, RealtekRTL8111.kext, WhateverGreen.kext, Lilu.kext, VirtualSMC.kext.
>   [hardinfo_config.zip](https://github.com/Broly1/tribeam/files/4644926/hardinfo_config.zip)
I don't know anything about laptops, sorry The Best way to get laptop support is here  https://discord.gg/N6tTXua

**Comment by siralexmu** [comment]
Thank you Broly1!

**Comment by Broly1** [comment]
I don't know anything about laptops, sorry The Best way to get laptop support is here  https://discord.gg/N6tTXua
